### ISSUE TITLE
discussion: canvas?

### ISSUE THREAD

**Issue by lukeed** [sindresorhus/osx-wallpaper#6]
Hi sindresorhus,

Sorry for opening an issue, but a friend and I were discussing whether or not it'd be possible to render/use HTML5 Canvas elements as wallpapers. 

Since you've dug around cross-platform wallpaper APIs & the discussion is _mostly_ on-topic, I figure I'd ask.

Thanks!

**Comment by sindresorhus** [comment]
Yes, you could use [`node-canvas`](https://github.com/Automattic/node-canvas) to render an image and then set it with [`wallpaper`](https://github.com/sindresorhus/wallpaper#api). If you're looking for something interactive, you'll have to do it in a running application. On OS X you can programmatically set a window as background, and you can put whatever in that window, including a webview with Canvas. You can actually do exactly this with Electron today, see https://github.com/electron/electron/pull/3509.

**Comment by lukeed** [comment]
Awesome! Thanks for the quick tip 😺
