### ISSUE TITLE
remote image support

### ISSUE THREAD

**Issue by marclundgren** [sindresorhus/osx-wallpaper#8]
I'd love to be able to download and set a remote desktop image.

```wallpaper http://imgur.com/a/DdV4w#VGgJD9O```

**Comment by sindresorhus** [comment]
Yeah, that would be nice. Belongs in https://github.com/sindresorhus/wallpaper-cli though. Can you move the issue there?

**Comment by marclundgren** [comment]
https://github.com/sindresorhus/wallpaper-cli/issues/2
